server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456

  jpa:
    show-sql: true
    properties:
      hibernate:
        formate-sql: true

jwt:
        secret: nckYV&%557Btjm#biYcES%buHv
        lifetime: 3600000



